apiVersion: v1
kind: Service
metadata:
  namespace: app
  name: {{ include "spring-helm-sample.fullname" . }}
  labels:
    {{- include "spring-helm-sample.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "spring-helm-sample.selectorLabels" . | nindent 4 }}
