name: CI
on:
  push:
    branches: [ "master" ]

env:
  FILE_PATH: /usr/local/deploy/
  HELM_CHART_PATH: spring-helm-chart

jobs:
  deploy-cp:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - run: rm -r -f $FILE_PATH$HELM_CHART_PATH
    - run: cp -r ./$HELM_CHART_PATH $FILE_PATH